# -*- coding: utf-8 -*-
"""online_food_delivery_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AxwBik71PXrsa6hbeWJq6AnJC_JBOD1L
"""

# Importing required libraries for data manipulation,analysis,and visualization

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read the original dataset and convert order_time to datetime

df=pd.read_csv("online_food_delivery_sales.csv",parse_dates=["order_time"])
print(df.shape)
print(df.head())
print(df.isnull().sum())
print(df.info())

df.rename(columns={'delivery_time_min':'deli_time','delivery_distance_km':'deli_dist','prep_time_min':'prep_time','final_amount':'revenue'},inplace=True)

# Feature engineering:deriving date, month, and weekday from order_time

df['date']=df['order_time'].dt.date
df['month']=df['order_time'].dt.month_name()
df['week_day']=df['order_time'].dt.day_name()
print(df["month"].unique())

print("total orders",len(df))
print("total revenue",df["revenue"].sum())

# CITY WISE ANALYSIS

city_Analysis=df.groupby('city').agg(total_order=("order_id","count"),total_revenue=("revenue","sum"),avg_delivery_time=("deli_time","mean"),avg_dist=("deli_dist","mean")).reset_index()

city_sorted = city_Analysis.sort_values(by=["total_order"],ascending=[False])

print(city_sorted.head(5))

order_day=df.groupby("week_day")["order_id"].count()
weekday_order=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
order_day=order_day.reindex(weekday_order)
print(order_day)

# Analyze order volume across different weekdays to identify peak ordering days

plt.figure(figsize=(8,6))
sns.barplot(x=order_day.index,y=order_day.values,hue=order_day.index,palette="coolwarm",legend=False)
plt.title("orders by weekday")
plt.xlabel("weekday")
plt.ylabel("total orders")
plt.xticks(rotation=45)
plt.show()

# Monthly order trend analysis to identify seasonal demand patterns and growth trends

monthly_orders=df.groupby("month")["order_id"].count().reset_index()
plt.figure(figsize=(12,4))
plt.plot(monthly_orders["month"],monthly_orders["order_id"],marker="o",color="red")
plt.title("Monthly Order Trend")
plt.xlabel("Months")
plt.ylabel("Number of Orders")
plt.show()

# RESTAURANT WISE ANALYSIS

restaurant_Analysis=df.groupby("restaurant").agg(total_order=("order_id","count"),total_revenue=("revenue","sum"),avg_prep_time=("prep_time","mean"),avg_rating=("rating","mean"),avg_discount=("discount_percent", "mean")).reset_index()
sorted_rest=restaurant_Analysis.sort_values(by=["avg_discount"],ascending=[False])
print(sorted_rest.head(5))

# Analyze total revenue generated by each city to compare market performance

citywise=df.groupby("city")["revenue"].sum()
plt.figure(figsize=(8,5))
sns.barplot(x=citywise.index,y=citywise.values,color="salmon")
plt.title("Total Revenue by City")
plt.xlabel("City")
plt.ylabel("Total Revenue")
plt.show()

# Analyzing cuisine-wise order volume and revenue across different cities

cuisine_Analysis=df.groupby(["cuisine","city"]).agg(total_order=("order_id","count"),total_price=("price","mean"),total_revenue=("revenue","sum"),avg_discount=("discount_percent", "mean")).reset_index()
cuisine_sorted=cuisine_Analysis.sort_values(by=["total_order"],ascending=[False])
print(cuisine_sorted.head(5))

# Identifying weekdays with higher promotional discounts

daywise_discount=df.groupby("week_day")["discount_percent"].mean()
weekday_order=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
daywise_discount = daywise_discount.reindex(weekday_order)
print(daywise_discount)
plt.figure(figsize=(8,5))
sns.barplot(x=daywise_discount.index,y=daywise_discount.values,hue=daywise_discount.index,palette="Blues",legend=False)
plt.title("Average Discount by Weekday")
plt.ylabel("Average Discount%")
plt.xlabel("Day of Week")
plt.xticks(rotation=45)
plt.show()

# Analyzing average discounts offered across different months

monthlywise=df.groupby("month")["discount_percent"].mean()
months=['January','February','March','April','May','June','July','August','September','October','November','December']
monthlywise=monthlywise.reindex(months)
print(monthlywise.head(10))
plt.figure(figsize=(14,5))
plt.plot(monthlywise.index,monthlywise.values,marker="o",color="Green")
plt.title("Average Discount Over Months")
plt.xlabel("Months",fontsize=14)
plt.ylabel("Average Discount(%)",fontsize=14)
plt.show()